### ISSUE TITLE
Which coordinate system?

### ISSUE THREAD

**Issue by TNA8** [hysts/pytorch_mpiigaze_demo#11]
I am trying to get on-screen 2d positions from 3d gaze vectors calculated mpiigaze.
I used mirror-based external camera calibration.
The 2d gaze vectors are very not accurate.

- The output 3d gaze vector is on head coordinate system or on NORMALIZED head coordinate system?

Thanks in advance.

**Comment by hysts** [comment]
Hi, @TiennAhn 

I think gaze vectors are computed in the camera coordinate system.

**Comment by TiennAhn** [comment]
The output gaze vector is in original camera coordinate system or normalized camera coordinate system?
I am still confusing.
If I need gaze vector in original camera coordinate system, which method can we use?
![screenshot_19](https://user-images.githubusercontent.com/58914448/141085559-0eb1c331-6a0b-4d48-9445-52747591f0c5.png)
![screenshot_20](https://user-images.githubusercontent.com/58914448/141085730-eb3efa8f-7e6e-404d-8a91-7c11e6cacbb8.png)

Could you make it clear?

**Comment by TiennAhn** [comment]
Can I directly use the calculated 3d gaze vector in calculating on-screen 2d gaze points?

**Comment by hysts** [comment]
@TNA8 
The raw output of the MPIIGaze model is in the normalized coordinate system, but it's post-processed to be in the original camera coordinate system.

See the following:
https://github.com/hysts/pytorch_mpiigaze_demo/blob/master/ptgaze/gaze_estimator.py#L97
https://github.com/hysts/pytorch_mpiigaze_demo/blob/master/ptgaze/common/face_parts.py#L39-L45

**Comment by TNA8** [comment]
![screenshot_21](https://user-images.githubusercontent.com/58914448/141092790-e3303155-a6a0-48e9-9406-a576c95e1443.png)
![screenshot_22](https://user-images.githubusercontent.com/58914448/141092797-76229321-cc76-456e-adbe-be5e8b98b4a1.png)

This is the real output values.
The values is very small, seems not in original camera system.

**Comment by hysts** [comment]
@TNA8 

The length of gaze vector is meaningless here. It's not that the end point of the gaze vector is the 3D point the person is looking at. It just means the person is looking at the direction the vector is pointing.

**Comment by TNA8** [comment]
Yes, but the `eye.center` value is almost (0, 0, 0). This could not be in original camera system.

**Comment by hysts** [comment]
@TNA8 

Ah, OK. As you underlined the origin and the end point, I thought you were talking about the length of the vector, but it wasn't.

You say the coordinate values are small, but it depends on which metric system is used, right? Here, the unit is meters (see [this](https://github.com/hysts/pytorch_mpiigaze_demo/blob/master/ptgaze/common/face_model_68.py#L21-L22)), so it actually looks like a decent value to me, though I'm not sure because the expected values depend on the input video you used.

**Comment by TNA8** [comment]
So  the final 3d gaze vector from the model is in `original` camera system and the unit is meter. Right?

**Comment by hysts** [comment]
Yes.

**Comment by TNA8** [comment]
Thanks a lot for your quick and kind explanation.

**Comment by younesmch** [comment]
@TNA8 i have the same problem as you 
can you help if you done for getting gaze on screen how you solve the problem
thnks
