### ISSUE TITLE
Using extrinsic camera matrix

### ISSUE THREAD

**Issue by TNA8** [hysts/pytorch_mpiigaze_demo#12]
![screenshot](https://user-images.githubusercontent.com/58914448/141072430-652fd754-7767-40cb-9c34-3f6ebd6f0de7.png)

When projecting 3d points in head coordinate system to pixel coordinate system, you set rotation and translation vector to zero.
This means head coordinate system is identical to camera coordinate system.
This is not reasonable.

* How can we calculate the extrinsic camera matrix for every frame? Those rotation and translation matrix varies for head pos.
For a specific images such as checkerboard pattern, OpenCV can calculate those matrix, but for face images...?

Thanks

**Comment by hysts** [comment]
@TiennAhn 

> When projecting 3d points in head coordinate system to pixel coordinate system, you set rotation and translation vector to zero.

Hmm... I think the code is projecting 3D points in the camera coordinate system to the pixel coordinate system.
Does that answer your question?

I'm not sure what you mean about extrinsic camera parameters. If you mean you want to know how the head pose in the camera coordinate system is computed, it's done by fitting a 3D model to the detected face landmarks. See [this part](https://github.com/hysts/pytorch_mpiigaze_demo/blob/master/ptgaze/common/face_model.py#L21-L43).

**Comment by TiennAhn** [comment]
If the cacluated 3d points is in camera coordinate system, it's okay.
I was confusing that the output of model is 3d points in head coordinate system, not in camera coordinate system.
