### ISSUE TITLE
Use it in python scripts

### ISSUE THREAD

**Issue by Tord-Zhang** [hysts/pytorch_mpiigaze_demo#13]
Is there a demo showing how to use it in python scripts? Thanks

**Comment by hysts** [comment]
Hi, @Tord-Zhang 

I think [this code](https://github.com/hysts/pytorch_mpiigaze_demo/blob/master/ptgaze/demo.py) would help you understand how to use the modules.

**Comment by eugeneYz** [comment]
> 

Hi, I also want to use this project in python. Did you apply it successfully?
