### ISSUE TITLE
I have a huge problem and I don't understand why because I'm a newby

### ISSUE THREAD

**Issue by CyrilGatino** [hysts/pytorch_mpiigaze_demo#14]
Hi,

First of all, thank you very much for your program.

My first question is : I want to estimate the gaze of my own picture (with 1, 2 or 3 persons). Does your program do this ? because I don't understand how to use it at all ? Sorry I'm new in coding.

Secondly, I have install ptgaze on my virtual machine (Virtual Box) with Ubuntu20.04 in it and I have tried to run this line code : 

python3 -m ptgaze --config /.local/lib/python3.8/site-packages/ptgaze/data/configs/mpiifacegaze.yaml

but it return me this : 

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/cyril/.local/lib/python3.8/site-packages/ptgaze/__main__.py", line 3, in <module>
    ptgaze.main.main()
  File "/home/cyril/.local/lib/python3.8/site-packages/ptgaze/main.py", line 129, in main
    config = OmegaConf.load(args.config)
  File "/home/cyril/.local/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 183, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/.local/lib/python3.8/site-packages/ptgaze/data/configs/mpiifacegaze.yaml'

but this FILE EXIST in this path... I really don't understand what to do after installing ptgaze to use it on my picture...

It's been 4 full days of work....

Thank you in advance for your time.

**Comment by hysts** [comment]
Hi, @CyrilGatino 

> My first question is : I want to estimate the gaze of my own picture (with 1, 2 or 3 persons). Does your program do this ?

Yes, this program can do it. For example, in my environment, when I run the following command, I get the image below:
```bash
wget https://raw.githubusercontent.com/hysts/pytorch_mpiigaze_demo/master/assets/inputs/image02.jpg
ptgaze --mode eth-xgaze --face-detector face_alignment_sfd --image image02.jpg -o out
```
![](https://user-images.githubusercontent.com/25161192/143782430-f7ba069a-35e4-48b5-b368-ad1e01239d9e.jpg)

As for the second point, your config path seems to be incorrect.
You are specifying the path `/.local/lib/python3.8/site-packages/ptgaze/data/configs/mpiifacegaze.yaml`, but I think it should be `~/.local/lib/python3.8/site-packages/ptgaze/data/configs/mpiifacegaze.yaml`.
The difference is `~`. I think [this link](https://twiki.org/cgi-bin/view/Wikilearn/TildeSlash) would help you understand what it is.

**Comment by CyrilGatino** [comment]
Hi @Hyst !

Thank you very much, I really appreciate your fast answer.

Everything works as you says.

I have just one more question, when you say in the readme page : "to train MPiigaze" it means that if I train the MPIIgaze with the database it will be better to detect eye's gaze of my own pictures ?

Thank you very much

**Comment by hysts** [comment]
@CyrilGatino 

> I have just one more question, when you say in the readme page : "to train MPiigaze" it means that if I train the MPIIgaze with the database it will be better to detect eye's gaze of my own pictures ?

I'm not entirely sure what you mean, but what I meant in the README is that there is a dataset called [MPIIGaze dataset](https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/research/gaze-based-human-computer-interaction/appearance-based-gaze-estimation-in-the-wild/), and [this repo](https://github.com/hysts/pytorch_mpiigaze) can be used to train a model with the dataset.
