### ISSUE TITLE
how to understand _compute_normalizing_rotation

### ISSUE THREAD

**Issue by CaichaoGitHub** [hysts/pytorch_mpiigaze_demo#15]
hi author, thanks your great work on gaze;
i'm not clear about the _compute_normalizing_rotation function:
can you give me some suggestions ?
![image](https://user-images.githubusercontent.com/12059897/146753179-c804f718-1040-46b7-81f4-f3fa1defc923.png)

**Comment by hysts** [comment]
Hi, @CaichaoGitHub 

The description in section 4.2 and Figure 9 of [this paper](https://arxiv.org/abs/1711.09017) will help you understand it.

**Comment by CaichaoGitHub** [comment]
thanks for reply !

**Comment by hysts** [comment]
No problem!
