### ISSUE TITLE
No module named ‘torchvision.models.utils‘ in ptgaze/models/mpiifacegaze/backbones/resnet_simple.py 

### ISSUE THREAD

**Issue by joqueka** [hysts/pytorch_mpiigaze_demo#16]
Hi,
running the demo with MPII FaceGaze returns an 'No module' error because torchvision seems to be restructured in newer versions. I found a solution right here:
https://stdworkflow.com/1260/no-module-named-torchvision-models-utils
If you replace _torchvision.models.utils.load_state_dict_from_url_ in **line 23** 
by _torch.hub.load_state_dict_from_url_ everything works fine.

**Comment by hysts** [comment]
Hi, @joqueka 

Thank you for reporting this. I've fixed it.
