### ISSUE TITLE
pitch and yaw (raw outputs of network) are not in HCS (head coordinates system)

### ISSUE THREAD

**Issue by ffletcherr** [hysts/pytorch_mpiigaze_demo#17]
Hi, thanks for this great implementation.

I recently tried to use the raw output of the network, which is trained on the ETH-XGaze dataset, to estimate the PoG (Point of Gaze) in CCS (Camera Coordinates System). So I used your normalization method and find the normalizing rotation matrix to transform the normalized gaze vector which is in HCS, to the 3D gaze vector which is in CCS.

But it seems that pitch and yaw are not in HCS because when everything is unchanging, except the camera position, the network output changes. So if it is correct and pitch and yaw are not in HCS, we need an extra step further than a normalizing rotation matrix which compensates head pose. But I can't find this step and it is ambiguous for me.

**Comment by hysts** [comment]
Hi, @ffletcherr 

The network outputs are not in HCS. I think you may be misunderstanding what the normalization method does. You can find a description of the normalization method in section 3.5 of [this paper](https://arxiv.org/abs/2007.15837). It says,
> In a nutshell, the data normalization method maps the input image to a normalized space where a virtual camera is used to warp the face patch out of the original input image according to 3D head pose. It rotates a virtual camera to cancel the head rotation around the row axis, and moves the virtual camera to a fixed distance from the face center to warp the face patch of fixed size.

Also, Figure 9 of [this paper](https://arxiv.org/abs/1711.09017) should help you understand.

**Comment by patrickshas** [comment]
Just a question: Figure 9 mentions a translation (s) and rotation (r) matrix. How could these two be accessed in the code? 

Also, are the pitch and yaw produced by the code in this head pose coordinate system? Your last answer is not clear. If not in the head pose coordinate system (or if yes), how could the camera coordinate system be transformed to the pitch and yaw output coordinate system?
