### ISSUE TITLE
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.

### ISSUE THREAD

**Issue by younesmch** [hysts/pytorch_mpiigaze_demo#18]
when i run it i get this error "OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized."
any one can help thnks

**Comment by younesmch** [comment]
it's just  add this two line in main.py
import os 
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"

and install numpy 1.18

**Comment by hysts** [comment]
Thanks for reporting this.
It looks like you've already solved the issue yourself. And it seems to be a problem with the dependency libraries or the Python environment.

**Comment by younesmch** [comment]
yes it is
