### ISSUE TITLE
question

### ISSUE THREAD

**Issue by nhathoang0110** [hysts/pytorch_mpiigaze_demo#2]
How can I modify the code in pygaze folder?

I have edited it but cannot apply when i run

**Comment by hysts** [comment]
Hi, @nhathoang0110 

I'm not sure I understand your question.
What modifications have you made?
I think the error message might be helpful.

**Comment by nhathoang0110** [comment]
Hello. It have not error. 
I have modified to print out some information but it doesn't do that. I guess it's because the program is installed and running using ptgaze so I fix the code directly and it doesn't get.

**Comment by nhathoang0110** [comment]
more specifically, what do I have to do to save all the image frames when I test the video

**Comment by hysts** [comment]
@nhathoang0110 

Ah, ok, now I think I understand now.
So, you've installed `ptgaze` by running `pip install ptgaze`, but you want to modify its behavior, so you cloned the repository, but it doesn't work after you made the change, right?

In that case, I think you can run the modified version in the `pytorch_mpiiigaze_demo` directory as follows,
```bash
python -m ptgaze --config /path/to/your/config.yaml
```

Or, you can uninstall the ptgaze first and then install your modified version by running the following command in the modified repo,

```bash
pip uninstall ptgaze
python setup.py install
```

**Comment by nhathoang0110** [comment]
oh it works. Thanks very much. My english is not good. Sorry and thanks you very much.
It's great

**Comment by hysts** [comment]
No problem. Glad to hear that. :)
