### ISSUE TITLE
static_image_mode using mediapipe 

### ISSUE THREAD

**Issue by joqueka** [hysts/pytorch_mpiigaze_demo#20]
Hi,
I'm using the Demo class by directly interacting with _process_image() function for batch processing of multiple images. However when using mediapipe as face and landmark detector it leads to erroneous results in this case. I found out this is due to mediapipe's default setting of STATIC_IMAGE_MODE in the FaceMesh API (for better performance). See https://google.github.io/mediapipe/solutions/face_mesh.html#static_image_mode

Regarding the current functionality with processing single images it is not a problem but I would recommend to set this parameter to true inside LandmarkEstimator initialization when input is an image. 

Thanks for the great work!

**Comment by Xscaaaper** [comment]
Hi,@joqueka  
 Hello, I am a python novice. I want to run the program and see the result, but I can't find the input video path. No error is reported but no result is displayed. I hope you can guide me, thank you!

**Comment by joqueka** [comment]
Hi @Xscaaaper 
this issue is the wrong place for this type of question. However I would recommend you to have a look at the config files. There you can set up everything without having to code anything in python, since the package can be run on command line.

**Comment by maolili981121** [comment]
Hello, I still want to ask, I'm in the defaults. Config folder The video input address is added to the PY file, but the main function runs without error, but there is no result. I am a novice. The questions I may ask are very simple. Please understand the inconvenience to you! I hope you can answer this question for me when you are free. Why does the main function run without results after adding a path. Thank you for your help!
![d29c489a7de8497c881600d776b4501](https://user-images.githubusercontent.com/91049552/158160223-bea724f1-81a8-4a70-9061-ed2557e60016.png)

**Comment by maolili981121** [comment]
Hi,@joqueka
Hello, I want to ask, I'm in the defaults. Config folder The video input address is added to the PY file, but the main function runs without error, but there is no result. I am a novice. The questions I may ask are very simple. Please understand the inconvenience to you! I hope you can answer this question for me when you are free. Why does the main function run without results after adding a path. Thank you for your help
![a542cc813ac6946680ba468c413e04c](https://user-images.githubusercontent.com/91049552/158180998-3e5cd4a1-92fd-4279-9ef8-f5a201882bb1.png)
!

**Comment by hysts** [comment]
@maolili981121 

Please don't ask unrelated questions in this issue. If you are still in a problem, please create a new issue. Then I will answer it there.
