### ISSUE TITLE
License and datasets

### ISSUE THREAD

**Issue by hovnatan** [hysts/pytorch_mpiigaze_demo#22]
Hi,

Great work and nice repo. Is it possible to use trained models and code in commercial setting? Can you please share the dataset for ETH XGaze? I cannot reach the authors of the paper.

Thanks!

**Comment by hysts** [comment]
Hi, @hovnatan 

The code is provided under the MIT license. So, commercial use is permitted as long as you comply with the license terms.
You need to read the license file carefully:
https://github.com/hysts/pytorch_mpiigaze_demo/blob/master/LICENSE

I am not a legal expert, so I can't say anything definitive about the licensing of the pretrained model. To be on the safe side, you should assume that it's under the [CC BY-NC-SA 4.0 license](https://creativecommons.org/licenses/by-nc-sa/4.0/).

Sharing and redistributing the ETH-XGaze dataset are not allowed. See the license terms:
https://ait.ethz.ch/projects/2020/ETH-XGaze/License.pdf

**Comment by hovnatan** [comment]
Ok, thanks!
