### ISSUE TITLE
How to determine drowsiness and yawning using ptgaze?

### ISSUE THREAD

**Issue by aaiguy** [hysts/pytorch_mpiigaze_demo#24]
Thanks for making ptgaze . I'm trying to determine whether the person is yawning or sleeping based on facial landmark features , I went through the code but I'm not able to achieve this,I wanted to know if this feature is implemented in this demo else can you point me out in right direction to achieve this?

**Comment by hysts** [comment]
Hi, @aaiguy 
No, this repo doesn't have a drowsiness detection function. Only simple gaze estimation is implemented in this repo.

The following repos may be helpful.
https://github.com/akshaybahadur21/Drowsiness_Detection
https://github.com/Tobias-Fischer/rt_gene
