### ISSUE TITLE
How to determine direction of point of view based on gaze estimation?

### ISSUE THREAD

**Issue by aaiguy** [hysts/pytorch_mpiigaze_demo#25]
How can I check if person is looking at straight ,left , right, up or down based on gaze estimation ? what variables must I monitor to achieve this? currently I can only see line pointing out direction on output frame suppose if person is seeing right side or left side I should print right or left side

**Comment by hysts** [comment]
Hi, @aaiguy 

I think that can be achieved by using the yaw and pitch angles of the gaze vector.
https://github.com/hysts/pytorch_mpiigaze_demo/blob/12f7aef0bc0271f59925e63e53e23d03e355e5a1/ptgaze/demo.py#L233-L234

**Comment by aaiguy** [comment]
@hysts thanks for reply, is there a scale sheet to determine which value of pitch yaw angle corresponds to which view(straight,left,right view)?

**Comment by hysts** [comment]
@aaiguy No. You need to determine thresholds for it yourself.
