### ISSUE TITLE
function associated with ptgaze library

### ISSUE THREAD

**Issue by patrickshas** [hysts/pytorch_mpiigaze_demo#26]
Hello,
Thank you for the amazing work!
Just wondering, regarding the ptgaze library, are there any associated functions which could be used within python code?
The readme only details the command line runnable demo.
Thanks in advance,
Best regards

**Comment by Hyrtsi** [comment]
@patrickshas what are you trying to do? Do you want to import this repository as a library and call the functions from your own code?

**Comment by patrickshas** [comment]
Hi,
Thank you for your reply.
Yes, exactly.
What are the callable functions? (If available)
Best

**Comment by hysts** [comment]
Hi, @patrickshas 
This repo may not be useful as a library because it was not my intension when I wrote the code. I guess some classes such as LandmarkEstimator, HeadPoseNormalizer, and GazeEstimator, could be of some use, but I'm not sure.
