### ISSUE TITLE
distortion coefficients:

### ISSUE THREAD

**Issue by yongwuSHU** [hysts/pytorch_mpiigaze_demo#3]
Thank you for the excellent work, I want to how can I get distortion coefficients, I find that is array [0,0,0,0,0,]. It is correct? I think it's not all zero.

**Comment by hysts** [comment]
Hi, @yongwuSHU 

You can calibrate your camera using a checkerboard pattern and OpenCV functions. I think following articles would be helpful.
https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_calib3d/py_calibration/py_calibration.html
https://www.learnopencv.com/camera-calibration-using-opencv/

**Comment by yongwuSHU** [comment]
hi, @hysts 
Thank your replay. If I got a video from internet, could I get the distortion coefficients by OpenCV functions?
Sorry to bother you.

**Comment by hysts** [comment]
@yongwuSHU 

I don't think it's possible to get the distortion coefficients in that case.

**Comment by yongwuSHU** [comment]
@hysts 
Thank you, actually, I want to pre-process the dataset EYEDIAP, it provided intrinsic parameters (martix 3*3), but no distortion coefficients. Could you give some ideas. Thank you.

**Comment by hysts** [comment]
@yongwuSHU 

In my understanding, cameras in EYEDIAP datasets are already undistorted, but i'm not 100% sure, so you might want to contact with the authors.

**Comment by yongwuSHU** [comment]
@hysts 
Thank you, trully. I have sent some emails to authors , but  no reponse. So, I can set distortion coefficients to [0,0,0,0,0] in your understanding?

**Comment by hysts** [comment]
@yongwuSHU 

Oh, I see.
Yes, I think it's OK to assume all distortion coefficients are zero.

**Comment by yongwuSHU** [comment]
@hysts 
Thank you very much.
