### ISSUE TITLE
CAMERA

### ISSUE THREAD

**Issue by liushifu12138** [hysts/pytorch_mpiigaze_demo#30]
(trt) lxy@aa-WS-C621E-SAGE-Series:~/pytorch_mpiigaze-master$ ptgaze --mode mpiifacegaze --camera CAMERA
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-9njnv3um because the default path (/home/lxy/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
INFO:ptgaze.main:mode: MPIIFaceGaze
device: cpu
model:
  name: resnet_simple
  backbone:
    name: resnet_simple
    pretrained: resnet18
    resnet_block: basic
    resnet_layers:
    - 2
    - 2
    - 2
face_detector:
  mode: mediapipe
  dlib_model_path: /home/lxy/.ptgaze/dlib/shape_predictor_68_face_landmarks.dat
  mediapipe_max_num_faces: 3
gaze_estimator:
  checkpoint: /home/lxy/.ptgaze/models/mpiifacegaze_resnet_simple.pth
  camera_params: CAMERA
  use_dummy_camera_params: false
  normalized_camera_params: /home/lxy/anaconda3/envs/trt/lib/python3.9/site-packages/ptgaze/data/normalized_camera_params/mpiifacegaze.yaml
  normalized_camera_distance: 1.0
  image_size:
  - 224
  - 224
demo:
  use_camera: true
  display_on_screen: true
  wait_time: 1
  image_path: null
  video_path: null
  output_dir: null
  output_file_extension: avi
  head_pose_axis_length: 0.05
  gaze_visualization_length: 0.05
  show_bbox: true
  show_head_pose: false
  show_landmarks: false
  show_normalized_image: false
  show_template_model: false
PACKAGE_ROOT: /home/lxy/anaconda3/envs/trt/lib/python3.9/site-packages/ptgaze

Traceback (most recent call last):
  File "/home/lxy/anaconda3/envs/trt/bin/ptgaze", line 8, in <module>
    sys.exit(main())
  File "/home/lxy/anaconda3/envs/trt/lib/python3.9/site-packages/ptgaze/main.py", line 152, in main
    check_path_all(config)
  File "/home/lxy/anaconda3/envs/trt/lib/python3.9/site-packages/ptgaze/utils.py", line 176, in check_path_all
    _check_path(config, 'gaze_estimator.camera_params')
  File "/home/lxy/anaconda3/envs/trt/lib/python3.9/site-packages/ptgaze/utils.py", line 167, in _check_path
    raise FileNotFoundError(f'config.{key}: {path.as_posix()} not found.')
FileNotFoundError: config.gaze_estimator.camera_params: CAMERA not found.

**Comment by hysts** [comment]
@liushifu12138 
You need to specify a camera calibration file as follows:
```bash
ptgaze --mode mpiifacegaze --camera camera_calibration.yaml
```

The camera calibration file must be in the same format as this sample file:
https://github.com/hysts/pytorch_mpiigaze_demo/blob/12f7aef0bc0271f59925e63e53e23d03e355e5a1/ptgaze/data/calib/sample_params.yaml#L1-L12

[This page](https://docs.opencv.org/4.x/d4/d94/tutorial_camera_calibration.html) may be helpful about how to perform camera calibration.
