### ISSUE TITLE
Face Model

### ISSUE THREAD

**Issue by enzoturletti** [hysts/pytorch_mpiigaze_demo#33]
Hello, first of all, great work in this application. It is possible to know the paper or the documentation where the face model is defined? (3D face model for Multi-PIE 68 points mark-up). I cant find it.

**Comment by hysts** [comment]
Hi, @enzoturletti 
I think [this dataset](http://www.cbsr.ia.ac.cn/users/xiangyuzhu/projects/3DDFA/main.htm) is relevant, but I don't remember how I obtained the 3D landmark points. I should have kept the code and data, but they are lost.
I think you can use [this library](https://github.com/1adrianb/face-alignment) to create one by applying the model to a lot of images, aligning detected face landmarks and averaging them.
