### ISSUE TITLE
different results if recorded video is used

### ISSUE THREAD

**Issue by jasony93** [hysts/pytorch_mpiigaze_demo#34]
Hello,

I am facing a weird problem.
The results I got from real-time inference and the results from recorded video are different.
I looked at the same spots from same position and used same camera.
The real-time inference shows reasonable results, but the results for the recorded video seems that the gaze has some amount of offset (it follows the gaze but with some offset)

Do you have any idea what the problem is?

**Comment by jasony93** [comment]
So far, I figured out that my real-time inference stream and recorded video inference have different resolutions.
It turns out that camera matrix has to be modified depending on the resolution. (that's what google said)

**Comment by hysts** [comment]
Hi, @jasony93 
Sorry for the late reply. I just noticed your comments.
It seems you have already solved the problem yourself. I think that's the cause too.
