### ISSUE TITLE
get gaze direction (top, top-bottom, etc) for the eyes or angles ( in 360 degrees coordinates )

### ISSUE THREAD

**Issue by elvis-kture** [hysts/pytorch_mpiigaze_demo#4]
How get the actual eyes direction from the pitch, raw info? 
Thanks

**Comment by hysts** [comment]
Hi, @elvis-kture 

Sorry for the late reply.
[Here](https://github.com/hysts/pytorch_mpiigaze_demo/blob/master/ptgaze/common/face_parts.py#L32-L38) is the code for converting gaze angle to 3D gaze vector.
