### ISSUE TITLE
ValueError, in "generate_dummy_camera_params" fuction of "utils.py"

### ISSUE THREAD

**Issue by basir-eb** [hysts/pytorch_mpiigaze_demo#6]
Hi, Thanks for your great project.
I faced this problem in version "0.2.2".
When you don't provide any path for video file or image file, which is the case you want to use webcam and live feed, program raises "ValueError" in "generate_dummy_camera_params" of utils.py. 
When video file is provided everything works fine.
I have tried to diagnose the problem, and I think it has something to do with dictionary passed to this function, in which both "image_path" and "video_path" keys are "None" and it causes this error.

`'demo': {'use_camera': True, 'display_on_screen': True, 'wait_time': 1, 'image_path': None, 'video_path': None, 'output_dir': None, 'output_file_extension': 'avi', 'head_pose_axis_length': 0.05, 'gaze_visualization_length': 0.05, 'show_bbox': True, 'show_head_pose': False, 'show_landmarks': False, 'show_normalized_image': False, 'show_template_model': False}`

**Comment by hysts** [comment]
@basir-eb 

Thank you very much! I fixed it.
