### ISSUE TITLE
Training code for ETH-XGAZE dataset

### ISSUE THREAD

**Issue by bakukaggle** [hysts/pytorch_mpiigaze_demo#9]
Hi, 
Would your provide the training code/scripts for ETH-XGAZE dataset?

**Comment by hysts** [comment]
@bakukaggle 

> Is there any preprocessing steps needed for ETH-XGAZE dataset?. Or I just use their provided ground truths to train model which is consistent with your demo code?

No, there isn't. So I think models trained with their code should work with this repo, but just to be sure, you might want to check first if their pretrained model works properly with this repo.
